require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContasController do

  # This should return the minimal set of attributes required to create a valid
  # Conta. As you add validations to Conta, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "dataAbertura" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all contas as @contas" do
      conta = Conta.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contas).should eq([conta])
    end
  end

  describe "GET show" do
    it "assigns the requested conta as @conta" do
      conta = Conta.create! valid_attributes
      get :show, {:id => conta.to_param}, valid_session
      assigns(:conta).should eq(conta)
    end
  end

  describe "GET new" do
    it "assigns a new conta as @conta" do
      get :new, {}, valid_session
      assigns(:conta).should be_a_new(Conta)
    end
  end

  describe "GET edit" do
    it "assigns the requested conta as @conta" do
      conta = Conta.create! valid_attributes
      get :edit, {:id => conta.to_param}, valid_session
      assigns(:conta).should eq(conta)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Conta" do
        expect {
          post :create, {:conta => valid_attributes}, valid_session
        }.to change(Conta, :count).by(1)
      end

      it "assigns a newly created conta as @conta" do
        post :create, {:conta => valid_attributes}, valid_session
        assigns(:conta).should be_a(Conta)
        assigns(:conta).should be_persisted
      end

      it "redirects to the created conta" do
        post :create, {:conta => valid_attributes}, valid_session
        response.should redirect_to(Conta.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved conta as @conta" do
        # Trigger the behavior that occurs when invalid params are submitted
        Conta.any_instance.stub(:save).and_return(false)
        post :create, {:conta => { "dataAbertura" => "invalid value" }}, valid_session
        assigns(:conta).should be_a_new(Conta)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Conta.any_instance.stub(:save).and_return(false)
        post :create, {:conta => { "dataAbertura" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested conta" do
        conta = Conta.create! valid_attributes
        # Assuming there are no other contas in the database, this
        # specifies that the Conta created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Conta.any_instance.should_receive(:update).with({ "dataAbertura" => "MyString" })
        put :update, {:id => conta.to_param, :conta => { "dataAbertura" => "MyString" }}, valid_session
      end

      it "assigns the requested conta as @conta" do
        conta = Conta.create! valid_attributes
        put :update, {:id => conta.to_param, :conta => valid_attributes}, valid_session
        assigns(:conta).should eq(conta)
      end

      it "redirects to the conta" do
        conta = Conta.create! valid_attributes
        put :update, {:id => conta.to_param, :conta => valid_attributes}, valid_session
        response.should redirect_to(conta)
      end
    end

    describe "with invalid params" do
      it "assigns the conta as @conta" do
        conta = Conta.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Conta.any_instance.stub(:save).and_return(false)
        put :update, {:id => conta.to_param, :conta => { "dataAbertura" => "invalid value" }}, valid_session
        assigns(:conta).should eq(conta)
      end

      it "re-renders the 'edit' template" do
        conta = Conta.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Conta.any_instance.stub(:save).and_return(false)
        put :update, {:id => conta.to_param, :conta => { "dataAbertura" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested conta" do
      conta = Conta.create! valid_attributes
      expect {
        delete :destroy, {:id => conta.to_param}, valid_session
      }.to change(Conta, :count).by(-1)
    end

    it "redirects to the contas list" do
      conta = Conta.create! valid_attributes
      delete :destroy, {:id => conta.to_param}, valid_session
      response.should redirect_to(contas_url)
    end
  end

end
